### ISSUE TITLE
permit_action no longer allows extra parameters?

### ISSUE THREAD

**Issue by arcreative** [punditcommunity/pundit-matchers#113]
Apologies if this was discussed on the roadmap somewhere, but we have policy methods that accept one (but conceivably more) attributes. 2.x would handle this fine, but 3.x throws the following error:

```
ArgumentError: wrong number of arguments (given 2, expected 1)

  0) CvEntryPolicy as a user with user's own record 
     Failure/Error: it { is_expected.to permit_action(:create_with_user, current_user) }

     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # /Users/arob/.gem/ruby/3.0.6/gems/pundit-matchers-3.1.2/lib/pundit/matchers.rb:71:in `permit_action'
     # ./spec/policies/cv_entry_policy_spec.rb:31:in `block (4 levels) in <top (required)>'
```

The use case is for the following policy method, invoked by https://github.com/venuu/jsonapi-authorization gem:

```ruby
  def create_with_user?(user)
    return false unless user_present?
    can_perform?(:user_administrate, [user.business_unit, user.location])
  end
```
